import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

var i = 0;
var txt = 'a Junior Developer and enthusiast for Blockchain and Data Science';
var speed = 50;

function typeWriter() {
  if (i < txt.length) {
    document.getElementById("demo").innerHTML += txt.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Victor Guidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    
        <h1 className={styles.title}>
          Hey there, welcome!
        </h1>

        <p className={styles.description}>
          Find out about some of my projects related to Data Science and Blockchain.
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/victorguidi?tab=repositories" className={styles.card}>
            <h2>Data Science projects &rarr;</h2>
            <p>Projects I developed using Python and R.</p>
          </a>

          <a href="https://github.com/victorguidi?tab=repositories" className={styles.card}>
            <h2>Blockchain Development &rarr;</h2>
            <p>Check out my projects for Ethereum and Solana!!</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/victorguidi"
          target="_blank"
          rel="noopener noreferrer"
        >
          About me - Victor Guidi
        </a>
      </footer>
    </div>
  )
}

/*<Image src="/background.png" alt="Vbackground" width={10} height={10} />*/